version: '3.8'

services:
  mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mqtt_data:/mosquitto/data
      - mqtt_log:/mosquitto/log
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - gateway_net

  backend:
    build: ./backend
    network_mode: host
    volumes:
      - ./backend/config:/app/backend/config
    environment:
      - MQTT_BROKER=127.0.0.1
      - MQTT_PORT=1883
    depends_on:
      - mqtt

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - gateway_net

networks:
  gateway_net:
    driver: bridge

volumes:
  mqtt_data:
  mqtt_log:
